/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/V6qnzuWGJHF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function HotelCard() {
  return (
    <Card className="flex flex-col md:flex-row items-start gap-4 p-4">
      <div className="md:w-full grid gap-4">
        <div>
          <h2 className="text-2xl font-bold">The Ritz-Carlton, Bali</h2>
          <p className="text-muted-foreground">Nusa Dua, Bali</p>
        </div>
        <div className="grid gap-2 grid-cols-3">
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>2 Bedrooms</span>
          </div>
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>2 Bathrooms</span>
          </div>
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>Free WiFi</span>
          </div>
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>Free Parking</span>
          </div>
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>Outdoor Pool</span>
          </div>
          <div className="flex items-center gap-2">
            <TickIcon />
            <span>Spa & Wellness Center</span>
          </div>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <StarIcon className="w-5 h-5 fill-primary" />
            <StarIcon className="w-5 h-5 fill-primary" />
            <StarIcon className="w-5 h-5 fill-primary" />
            <StarIcon className="w-5 h-5 fill-primary" />
            <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            <span className="text-sm font-medium">4.7 (1,234 reviews)</span>
          </div>
          <div className="text-2xl font-bold">$499</div>
        </div>
        <Button size="lg" className="w-full">
          Book Now
        </Button>
      </div>
    </Card>
  );
}

function TickIcon() {
  return (
    <svg
      className="w-5 h-5"
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 13l4 4L19 7" />
    </svg>
  );
}

type IconProps = {
  className?: string;
};

function StarIcon({ className }: IconProps) {
  return (
    <svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
