/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/St2dipzxlyt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";

type Props = {
  location: string;
  condition: string;
  temperature: number;
  description: string;
};
export function WeatherCard({
  location,
  condition,
  temperature,
  description,
}: Props) {
  return (
    <Card className="w-1/2 p-6 grid gap-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="bg-gray-300 rounded-md p-3 flex items-center justify-center">
            <CloudIcon />
          </div>
          <div>
            <h3 className="text-xl font-semibold">{location}</h3>
            <p className="text-muted-foreground">{condition}</p>
            <p className="text-muted-foreground">{description}</p>
          </div>
        </div>
        <div className="text-4xl font-bold">{temperature}°</div>
      </div>
    </Card>
  );
}

function CloudIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      className="size-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M2.25 15a4.5 4.5 0 0 0 4.5 4.5H18a3.75 3.75 0 0 0 1.332-7.257 3 3 0 0 0-3.758-3.848 5.25 5.25 0 0 0-10.233 2.33A4.502 4.502 0 0 0 2.25 15Z"
      />
    </svg>
  );
}
